apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: web-app
  name: web-app
---
apiVersion: v1
kind: Service
metadata:
  name: node-web-app
  namespace: web-app
spec:
  ports:
  - port: 80
    targetPort: node-port
    protocol: TCP
  selector:
    app: node-web-app
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-web-app
  namespace: web-app
  labels:
    app: node-web-app
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.node-web-app: semver:~1.0.0
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: node-web-app
  template:
    metadata:
      labels:
        app: node-web-app
    spec:
      containers:
      - name: node-web-app
        image: gynther/node-web-app:1.0.1
        ports:
        - name: node-port
          containerPort: 8080
